### ISSUE TITLE
macOS Sierra broken notification suppression

### ISSUE THREAD

**Issue by ewellinger** [JordanMajd/hammerspoon#4]
It seems as though setting Hammerspoon to Awake no longer is suppressing notification properly.  I tried replacing 

```
hs.execute("launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist")
```

with...

```
hs.execute("defaults -currentHost write ~/Library/Preferences/ByHost/com.apple.notificationcenterui doNotDisturb -boolean true && killall NotificationCenter")
``` 

but that doesn't appear to have worked either.  I'm also noticing that hammerspoon isn't auto reloading the config either, but that's not as big of an issue.

**Comment by JordanMajd** [comment]
Thanks, I'll dig into this sometime in the next couple weeks.
